services:
  client:
    build: .
    container_name: loader-client
    env_file: .env
    command: bash -c "alembic upgrade head && tgloader --run=client"
    restart: always
  bot:
    build: .
    container_name: loader-bot
    env_file: .env
    command: tgloader --run=bot
    restart: always
    depends_on:
      - client
