services:
  bot:
    build: .
    container_name: loader-bot
    env_file: prod.ini
    command: tgloader --run=bot
    restart: always
    depends_on:
      - client
  client:
    build: .
    container_name: loader-client
    env_file: prod.ini
    command: tgloader --run=client
    restart: always
