import enum


class Queue(enum.StrEnum):
    PRE_YOUTUBE = "PRE_YOUTUBE"
    DOWNLOAD_YOUTUBE = "DOWNLOAD_YOUTUBE"
    YOUTUBE_CACHE = "YOUTUBE_CACHE"
    FINAL_COMMON_MEDIA = "FINAL_COMMON_MEDIA"
    ERRORS = "ERRORS"
    SAVE_YOUTUBE = "SAVE_YOUTUBE"
