"""create tables

Revision ID: 60035960d9f4
Revises:
Create Date: 2024-08-13 16:38:43.921427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60035960d9f4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("video_id", sa.String(length=256), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("video_id"),
        sa.UniqueConstraint("file_id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=True),
        sa.Column("last_name", sa.String(length=256), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_file",
        sa.Column("user_fk", sa.BigInteger(), nullable=False),
        sa.Column("file_fk", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_fk"], ["file.video_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_fk"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_fk", "file_fk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_file")
    op.drop_table("user")
    op.drop_table("file")
    # ### end Alembic commands ###
