name: Deploy to Server

on:
  workflow_dispatch:
  
jobs:
  deploy:
    name: start deploy
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.SSH_USER }}
    steps:
      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -p $PORT -H $HOST > ~/.ssh/known_hosts
      - name: connect ssh & pull & docker rebuilding
        run: |
          ssh $USER@$HOST -p $PORT \
          "cd tgloader \
          && git pull \
          && docker-compose up -d --build --no-deps \
          && docker system prune -fa \
          && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
