name: CI
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: djskfj
        run: echo Hello GH Actions!
  build_and_push:
    runs-on: ubuntu-latest
  deploy:
    runs-on: ubuntu-latest
